import json
import tempfile
import os
import logging
import requests
from typing import Dict, Any
from tools import check_tool, run_command

logger = logging.getLogger(__name__)


def scan_firewall(url: str) -> Dict[str, Any]:
    """Detect WAF using wafw00f CLI. Falls back to header-based detection."""
    if check_tool('wafw00f'):
        return _wafw00f_scan(url)
    return _header_scan(url)


def _wafw00f_scan(url: str) -> Dict[str, Any]:
    """Run wafw00f with JSON output."""
    tmp = tempfile.NamedTemporaryFile(suffix='.json', delete=False)
    tmp.close()
    try:
        success, stdout, stderr = run_command(
            ['wafw00f', url, '-a', '-o', tmp.name, '-f', 'json'],
            timeout=30
        )
        if os.path.exists(tmp.name) and os.path.getsize(tmp.name) > 0:
            with open(tmp.name) as f:
                data = json.load(f)
            if isinstance(data, list) and data:
                entry = data[0]
                detected = bool(entry.get('detected'))
                waf_name = entry.get('firewall') or 'None'
                manufacturer = entry.get('manufacturer') or ''
                return {
                    'detected': detected,
                    'waf_name': waf_name if detected else 'No WAF detected',
                    'manufacturer': manufacturer,
                    'confidence': 'High' if detected else 'None',
                }
    except Exception as e:
        logger.debug("wafw00f scan error: %s", e)
    finally:
        if os.path.exists(tmp.name):
            try:
                os.unlink(tmp.name)
            except OSError:
                pass

    logger.warning("wafw00f output unusable for %s, falling back to header scan", url)
    return _header_scan(url)


def _header_scan(url: str) -> Dict[str, Any]:
    """Fallback: detect WAF from HTTP response headers and body."""
    WAF_SIGNATURES = {
        'Cloudflare':         ['cf-ray', 'cf-cache-status'],
        'AWS WAF':            ['x-amz-cf-id', 'x-amzn-requestid', 'x-amzn-waf-id'],
        'Akamai':             ['akamai-origin-hop', 'x-akamai-transformed', 'x-akamai-request-id'],
        'Imperva/Incapsula':  ['x-iinfo', 'incapsula', 'x-cdn'],
        'Sucuri':             ['x-sucuri-id', 'x-sucuri-cache'],
        'Fastly':             ['x-served-by', 'fastly-restarts', 'x-fastly-request-id'],
        'DDoS-Guard':         ['ddos-guard'],
        'Barracuda':          ['barra_counter_session'],
        'F5 BIG-IP':          ['bigipserver', 'x-wa-info', 'f5-bigip'],
        'ModSecurity':        ['mod_security', 'modsecurity'],
        'Google Cloud Armor': ['x-goog-generation', 'x-cloud-trace-context', 'via'],
        'Azure Front Door':   ['x-azure-ref', 'x-fd-health', 'x-azure-fdid'],
        'StackPath':          ['x-sp-', 'x-hw'],
        'Citrix NetScaler':   ['ns-', 'citrix'],
        'FortiWeb':           ['fortiwafsid', 'fortigate'],
        'Wallarm':            ['x-wallarm-'],
        'Reblaze':            ['rbzid'],
        'Varnish':            ['x-varnish', 'via'],
        'Wordfence':          ['x-wf-', 'x-fw-'],
        'Nginx ModSecurity':  ['x-modsec'],
    }

    BODY_SIGNATURES = {
        'Cloudflare':    ['cloudflare', 'cf-browser-verification', 'cf-challenge'],
        'Akamai':        ['akamaighost', 'reference #', 'access denied'],
        'Imperva':       ['incapsula', '_Incapsula_Resource'],
        'Sucuri':        ['sucuri', 'access denied', 'blocked by sucuri'],
        'Wordfence':     ['wordfence', 'generated by wordfence'],
        'AWS WAF':        ['aws', 'x-amzn-error'],
        'ModSecurity':   ['modsecurity', 'mod_security', 'not acceptable'],
        'F5 BIG-IP':     ['bigip', 'f5 networks'],
        'DDoS-Guard':    ['ddos-guard', 'ddos-guard.net'],
        'Azure Front Door': ['azure', 'x-azure-ref'],
    }

    try:
        resp = requests.get(url, timeout=10, headers={
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
        }, allow_redirects=True)

        headers_lower = {k.lower(): v.lower() for k, v in resp.headers.items()}
        headers_keys = set(headers_lower.keys())
        headers_values = ' '.join(headers_lower.values())
        body_lower = resp.text.lower()

        # Check header keys
        for waf_name, signatures in WAF_SIGNATURES.items():
            for sig in signatures:
                if any(sig in key for key in headers_keys):
                    return {
                        'detected': True,
                        'waf_name': waf_name,
                        'manufacturer': waf_name,
                        'confidence': 'Medium',
                    }

        # Check header values
        for waf_name, signatures in WAF_SIGNATURES.items():
            for sig in signatures:
                if sig in headers_values:
                    return {
                        'detected': True,
                        'waf_name': waf_name,
                        'manufacturer': waf_name,
                        'confidence': 'Low',
                    }

        # Check body content
        for waf_name, signatures in BODY_SIGNATURES.items():
            for sig in signatures:
                if sig in body_lower:
                    return {
                        'detected': True,
                        'waf_name': waf_name,
                        'manufacturer': waf_name,
                        'confidence': 'Low',
                    }

        # Check for block pages (common WAF response patterns)
        if resp.status_code in [403, 406, 429, 503]:
            block_indicators = ['blocked', 'denied', 'forbidden', 'access denied',
                                'security', 'firewall', 'waf', 'challenge']
            if any(indicator in body_lower for indicator in block_indicators):
                return {
                    'detected': True,
                    'waf_name': 'Unknown WAF',
                    'manufacturer': 'Unknown',
                    'confidence': 'Low',
                }

        return {
            'detected': False,
            'waf_name': 'No WAF detected',
            'manufacturer': '',
            'confidence': 'Medium',
        }
    except Exception as e:
        logger.debug("Header scan error for %s: %s", url, e)
        return {
            'detected': False,
            'waf_name': 'Unknown',
            'manufacturer': '',
            'confidence': 'None',
            'error': str(e),
        }
